# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Docusaurus Build Test

on: 
  workflow_dispatch:
  pull_request:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "*" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout out parent repo
      uses: actions/checkout@v4
      with: "anitabi/navi.anitabi.cn"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        path: docs
    - run: npm ci
    - run: npm run build --if-present