---
name: Submodule Updates

on:
  workflow_run:
      workflows: [CI]
      branches: [master]
      types:
        - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: run action
        id: run_action
        uses: PaulRitter/github-action-create-commit-parent-submodule@v2.0
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          parent_repository: anitabi/navi.anitabi.cn
          parent_branch: master